version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: fsw-foods-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data

  neon:
    image: perconalab/neon:latest
    container_name: fsw-foods-neon
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "50051:50051"
    depends_on:
      - postgres

volumes:
  .postgres-data:
